spring:
  application:
    name: PicPay
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3333/banco}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true



